# Generated by Django 4.0.2 on 2022-02-02 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoProfile',
            field=models.FileField(blank=True, null=True, upload_to='images/profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])]),
        ),
    ]
