# Generated by Django 4.0.2 on 2022-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_photoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('principal', 'principal'), ('secondaire', 'secondaire')], default='principal', max_length=100),
        ),
    ]
