# Generated by Django 4.0.2 on 2022-02-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='fichier_pdf_genere',
            field=models.FileField(blank=True, null=True, upload_to='RapportsPDF/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
