# Generated by Django 4.0.2 on 2022-02-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_rapport_fichier_pdf_genere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
