# Generated by Django 4.0.2 on 2022-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='affaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='tf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
