# Generated by Django 4.0.2 on 2022-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0002_rapport_affaire_rapport_date_rapport_tf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
