# Generated by Django 4.0.2 on 2022-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0003_alter_rapport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='refernce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
