# Generated by Django 4.0.2 on 2022-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0004_rapport_refernce'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='code_rapport',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
