# Generated by Django 4.0.2 on 2022-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0005_rapport_code_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='valorisation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='code_rapport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
