# Generated by Django 4.0.2 on 2022-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0006_rapport_valorisation_alter_rapport_code_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='tf',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
